import Footer from "@/components/Footer";
import MainNav from "@/components/MainNav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-neutral-800 dark:text-neutral-300 bg-neutral-100 dark:bg-neutral-950 body-font min-h-screen max-w-screen overflow-x-hidden">
        <div className="relative grid grid-cols-1 sm:grid-cols-[3.5rem,_1fr]">
          <MainNav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
